language: ruby
cache: bundler
rvm:
  - 2.5

before_install:
  - openssl aes-256-cbc -K $encrypted_83b16eff69e4_key -iv $encrypted_83b16eff69e4_iv -in entry.dat.enc -out lich/data/entry.dat -d
  - bundle update --bundler

script:
  - bin/index_shops
  - find lich/logs -name "*.log" -print | xargs cat

# https://docs.travis-ci.com/user/deployment/surge/
deploy:
  skip_cleanup: true
  provider: surge
  project: lich/bodega
  domain: bodega.surge.sh
